In [1]:
print("Hello World")

Hello World


In [2]:
a = 10
b = 20
print (a+b)

30


a = 10
b = 20
print (a+b)

a = 10
b = 20
print (a+b)

a = 10
b = 20
print (a+b)

python3 --version

In [1]:
import numpy as np
from sklearn import preprocessing
#We imported a couple of packages. Let's create some sample data and add the line to this file:
input_data = np.array([[3, -1.5, 3, -6.4], [0, 3, -1.3, 4.1], [1, 2.3, -2.9, - 4.3]])

ModuleNotFoundError: No module named 'sklearn'

In [2]:
conda install scikit-learn

Retrieving notices: ...working... done
Solving environment: done

## Package Plan ##

  environment location: /Users/prashantnerkar/opt/anaconda3/envs/automation

  added / updated specs:
    - scikit-learn


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2022.12.7          |  py310hecd8cb5_0         151 KB
    joblib-1.1.1               |  py310hecd8cb5_0         387 KB
    libgfortran-5.0.0          |11_3_0_hecd8cb5_28         142 KB
    libgfortran5-11.3.0        |      h9dfd629_28         1.4 MB
    scikit-learn-1.1.3         |  py310he9d5cce_0         6.6 MB
    scipy-1.9.3                |  py310h09290a1_0        20.6 MB
    ------------------------------------------------------------
                                           Total:        29.3 MB

The following NEW packages will be INSTALLED:

  fftw               pkgs/main/osx-64::fftw-3.3.9-h9ed2024_1 
  joblib        

In [3]:
import numpy as np
from sklearn import preprocessing
#We imported a couple of packages. Let's create some sample data and add the line to this file:
input_data = np.array([[3, -1.5, 3, -6.4], [0, 3, -1.3, 4.1], [1, 2.3, -2.9, - 4.3]])

In [5]:
data_standardized = preprocessing.scale(input_data)
print ("\nMean =", data_standardized.mean(axis=0))
print ("Std deviation =", data_standardized.std(axis=0))


Mean = [ 5.55111512e-17 -3.70074342e-17  0.00000000e+00 -1.85037171e-17]
Std deviation = [1. 1. 1. 1.]


In [6]:
data_scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled = data_scaler.fit_transform(input_data)
print ("\nMin max scaled data =", data_scaled)


Min max scaled data = [[1.         0.         1.         0.        ]
 [0.         1.         0.27118644 1.        ]
 [0.33333333 0.84444444 0.         0.2       ]]


In [7]:
data_normalized = preprocessing.normalize(input_data, norm='l1')
print ("\nL1 normalized data =", data_normalized)


L1 normalized data = [[ 0.21582734 -0.10791367  0.21582734 -0.46043165]
 [ 0.          0.35714286 -0.1547619   0.48809524]
 [ 0.0952381   0.21904762 -0.27619048 -0.40952381]]


In [9]:
data_binarized = preprocessing.Binarizer(threshold=1.4).transform(input_data)
print ("\nBinarized data =", data_binarized)


Binarized data = [[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 1. 0. 0.]]


In [10]:
encoder = preprocessing.OneHotEncoder()
encoder.fit([[0, 2, 1, 12], [1, 3, 5, 3], [2, 3, 2, 12], [1, 2, 4, 3]])
encoded_vector = encoder.transform([[2, 3, 5, 3]]).toarray()
print ("\nEncoded vector =", encoded_vector)


Encoded vector = [[0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0.]]
